package com.jbk.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
@Entity
public class Employee {
	                 @Id
	                 @GeneratedValue(strategy=GenerationType.AUTO)
					private Long id; // => primary => autogenerated
	                 @Column(nullable=false)
					private String name;
	                 @Column(nullable=false)
					private String emailid;
	                 @Column(nullable=false)
					private int mobile_no;
	                 @Column(nullable=false)
	                private String status;// => data => active/inactive/suspend
	                 @Column(nullable=false)
					private String department;
	                 @Column(nullable=false)
					private String createdDate; // => data => date
	                 @Column(nullable=false)
					private String createdBy; // => name
	                 @Column(nullable=false)
					private String updatatedDate; // =>data => date
	                 @Column(nullable=false)
					private String updatatedby; // => name
					@OneToOne
					@JoinColumn(name="cid")
					private Country cid; // => one to one
					public Employee() {
						// TODO Auto-generated constructor stub
					}
					public Employee(Long id, String name, String emailid, int mobile_no, String status,
							String department, String createdDate, String createdBy, String updatatedDate,
							String updatatedby, Country cid) {
						super();
						this.id = id;
						this.name = name;
						this.emailid = emailid;
						this.mobile_no = mobile_no;
						this.status = status;
						this.department = department;
						this.createdDate = createdDate;
						this.createdBy = createdBy;
						this.updatatedDate = updatatedDate;
						this.updatatedby = updatatedby;
						this.cid = cid;
					}
					public Long getId() {
						return id;
					}
					public void setId(Long id) {
						this.id = id;
					}
					public String getName() {
						return name;
					}
					public void setName(String name) {
						this.name = name;
					}
					public String getEmailid() {
						return emailid;
					}
					public void setEmailid(String emailid) {
						this.emailid = emailid;
					}
					public int getMobile_no() {
						return mobile_no;
					}
					public void setMobile_no(int mobile_no) {
						this.mobile_no = mobile_no;
					}
					public String getStatus() {
						return status;
					}
					public void setStatus(String status) {
						this.status = status;
					}
					public String getDepartment() {
						return department;
					}
					public void setDepartment(String department) {
						this.department = department;
					}
					public String getCreatedDate() {
						return createdDate;
					}
					public void setCreatedDate(String createdDate) {
						this.createdDate = createdDate;
					}
					public String getCreatedBy() {
						return createdBy;
					}
					public void setCreatedBy(String createdBy) {
						this.createdBy = createdBy;
					}
					public String getUpdatatedDate() {
						return updatatedDate;
					}
					public void setUpdatatedDate(String updatatedDate) {
						this.updatatedDate = updatatedDate;
					}
					public String getUpdatatedby() {
						return updatatedby;
					}
					public void setUpdatatedby(String updatatedby) {
						this.updatatedby = updatatedby;
					}
					public Country getCid() {
						return cid;
					}
					public void setCid(Country cid) {
						this.cid = cid;
					}
					@Override
					public String toString() {
						return "Employee [id=" + id + ", name=" + name + ", emailid=" + emailid + ", mobile_no="
								+ mobile_no + ", status=" + status + ", department=" + department + ", createdDate="
								+ createdDate + ", createdBy=" + createdBy + ", updatatedDate=" + updatatedDate
								+ ", updatatedby=" + updatatedby + ", cid=" + cid + "]";
					}
					

}
